# Generated by Django 4.2.7 on 2023-12-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplikasiLayananUMKM', '0004_ayamgeprek_esjeruk_esteh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EsJeruk',
            new_name='EsBuah',
        ),
    ]
